### ISSUE TITLE
Modify names of classes

### ISSUE THREAD

**Issue by acvirts** [mucs420f19/HyperTextAssassins#15]
Give the user the ability to modify/edit the names of pre-existing classes.

Primary: Andrew
Secondary: Tristan

Hours: 3

**Comment by acvirts** [comment]
Spent 3 hours working on this task

**Comment by TristanKieffer** [comment]
Spent 2 hours working on this task

**Comment by SeanMcMVille** [comment]
Worked about ten minutes
Issue duped
