### ISSUE TITLE
Framework of class and constructor 

### ISSUE THREAD

**Issue by LaurenKieffer95** [mucs420f19/HyperTextAssassins#4]
2hrs 

Primary: Tristan 
Secondary: Andrew
    Hours spent working-Andrew: 2 hours

**Comment by TristanKieffer** [comment]
Spent 3 hours working on this task

**Comment by acvirts** [comment]
Spent 1 hour working on this

**Comment by SeanMcMVille** [comment]
Worked about 10 minutes
