### ISSUE TITLE
Show function name, its parameters, and its return type in the GUI

### ISSUE THREAD

**Issue by TristanKieffer** [mucs420f19/HyperTextAssassins#49]
Primary: Andrew
Secondary: Tristan
Time: 3 hours

**Comment by acvirts** [comment]
Worked on this for 2 hours today

**Comment by acvirts** [comment]
Worked on this for 5 hours yesterday

**Comment by acvirts** [comment]
Spent 5 hours working on and updating/fixing this today

**Comment by TristanKieffer** [comment]
Worked on this for about 12 hours
