### ISSUE TITLE
Setting a name for a block and check for duplicates

### ISSUE THREAD

**Issue by LaurenKieffer95** [mucs420f19/HyperTextAssassins#5]
2hrs

Primary: Andrew
    Hours spent working-Andrew: 3 
Secondary: Tristan

**Comment by acvirts** [comment]
Spent 3 hours working on and debugging this task

**Comment by TristanKieffer** [comment]
Spent 2 hours working on this

**Comment by SeanMcMVille** [comment]
Worked about 1 hour
